### ISSUE TITLE
Undo does not undo automatic table pointer changes caused by table row insertion

### ISSUE THREAD

**Issue by acrouzet** [jpage8580/GTUltra#49]

**Comment by jpage8580** [comment]
Have fixed now. Thanks for reporting that one!

**Comment by acrouzet** [comment]
It appears that undo still does not properly undo automatic table pointer changes caused by table row insertion.

**Comment by jpage8580** [comment]
Hopefully fixed now

**Comment by marcinkubica** [comment]
@acrouzet fixed?

**Comment by acrouzet** [comment]
It seems somewhat fixed. I still get problems when undoing sometimes.
